### PR TITLE
Fix UI freezes

### LINKED ISSUE #315: UI freezes while BG operations are performed
I made 2 videos to show you what's happened on our smarthone for Wallabag when the network does a "yo-yo" (go away / come back)

On the second one, you will see "black" or "white" screen.
This is not due to the video encoding. It's the real effect I could notice when the smartphone looses is breath. To fix this behavior I finally have to remove Wallabag from the recent app I launched.
You can see the time elasped in the footer of the video, showing you the real time I have to wait before being able to do anything

https://foxmask.trigger-happy.eu/static/wallabag/2016_10_04_07_40_18.mp4
https://foxmask.trigger-happy.eu/static/wallabag/2016_10_04_07_41_58.mp4

### PR DESCRIPTION
**Pull request by di72nn**
I rewrote something I wanted to rewrite almost from the beginning of #282.

Action processing before this PR (does not apply to "sync queue" and "update feeds" actions):
 1. *(DB transaction is started here).*
 1. The offline queue is checked.
 1. If the action wasn't canceled out by queue contents, an attempt to transmit the action to server is performed.
 1. If the transmission fails, the action is added to the offline queue.
 1. *(DB transaction is ended here).*
 1. ...
 1. The queue is synced sometime later.

After this PR:
 1. *(This is done inside of one short DB transaction)* The offline queue is checked. If the action is not canceled out, it is added to the queue.
 1. If the queue is not empty, "sync offline queue" action is triggered.
 1. The queue is synced *(using only one short DB transaction to write changes at the end)*.

Essentially, the queue sync is the only way to pass local changes to the server. That change allowed to remove a lot of code duplication. And it also allowed to remove most of the DB transactions that presumably caused UI freezes. 
Though, the is a limitation: the is no (easy?) way to get the action result for a specific action. But it was barely used anyway.

Fixes #315.

### CODE REVIEW

File: app/src/main/java/fr/gaulupeau/apps/Poche/service/BGService.java [hunk 1]
```diff
@@ -58,54 +58,40 @@ public BGService() {
...
-                } finally {
-                    removeStickyEvent(startEvent);
-                    if(result == null) result = new ActionResult(ActionResult.ErrorType.Unknown);
-                    postEvent(new SyncQueueFinishedEvent(actionRequest, result));
+            case Archive:
+            case Unarchive:
+            case Favorite:
+            case Unfavorite:
+            case Delete:
+            case AddLink:
```
Comment (tcitworld) [inline app/src/main/java/fr/gaulupeau/apps/Poche/service/BGService.java]: There's no way to improve this switch condition ?

**Comment by tcitworld** [comment]
Will test asap.

File: app/src/main/java/fr/gaulupeau/apps/Poche/service/BGService.java (hunk 1 above)
Comment (di72nn) [inline app/src/main/java/fr/gaulupeau/apps/Poche/service/BGService.java]: I considered moving these into the `default` case (another check is done inside of `serveSimpleRequest()` anyway), but I don't see improvements in such move. I thought that it will be easier to make a decision when there will be need to change this part again.

File: app/src/main/java/fr/gaulupeau/apps/Poche/events/SyncQueueFinishedEvent.java [hunk 2]
```diff
@@ -6,6 +6,7 @@
 public class SyncQueueFinishedEvent extends BackgroundOperationEvent {
 
     protected ActionResult result;
+    protected Long queueLength;
```
Comment (di72nn) [inline app/src/main/java/fr/gaulupeau/apps/Poche/events/SyncQueueFinishedEvent.java]: I use object types instead of primitives types when I need `null` to be a possible value (like "the value is not set"). Otherwise instead of `null` I would probably need to use some "special values" like `-1` which may not be always obvious to use in conditions. `value != null` is pretty much obvious no matter what.
When I'm sure the value is always set, I stick with primitive types.

File: app/src/main/java/fr/gaulupeau/apps/Poche/service/BGService.java [hunk 3]
```diff
@@ -124,402 +110,232 @@ protected void onHandleIntent(Intent intent) {
...
-        } finally {
-            daoSession.getDatabase().endTransaction();
         }
 
-        if(queueChangedLength != null) {
-            postEvent(new OfflineQueueChangedEvent(queueChangedLength));
+        if(queueLength != null) {
+            postEvent(new OfflineQueueChangedEvent(queueLength));
+        } else {
+            queueLength = (long)queueItems.size();
```
Comment (di72nn) [inline app/src/main/java/fr/gaulupeau/apps/Poche/service/BGService.java]: I cast `int` to `long` so the compiler could implicitly cast it to `Long`. You can't directly cast `int` to `Long`, though.

You can try `Long.valueOf(queueItems.size())`, but Android Studio will suggest to replace it with `(long)`. You can also use `(Long)(long)`, but that's just redundant.

File: app/src/main/java/fr/gaulupeau/apps/Poche/events/EventProcessor.java [hunk 4]
```diff
@@ -202,6 +205,12 @@ public void onSyncQueueFinishedEvent(SyncQueueFinishedEvent event) {
 
         getNotificationManager().cancel(TAG, NOTIFICATION_ID_SYNC_QUEUE_ONGOING);
 
+        ActionResult result = event.getResult();
+        if(result != null && !result.isSuccess()
```
Comment (di72nn) [inline app/src/main/java/fr/gaulupeau/apps/Poche/events/EventProcessor.java]: Done.

File: app/src/main/java/fr/gaulupeau/apps/Poche/service/BGService.java (hunk 3 above)
Comment (Strubbl) [inline app/src/main/java/fr/gaulupeau/apps/Poche/service/BGService.java]: Thank you
