### PR TITLE
Lazy loading of article `content` and full-text search

### LINKED ISSUE #413: IllegalStateException: Couldn't read row 0, col 0 from CursorWindow (in GreenDAO's list method)
From google play dev console:
Application version: 29.
Android version: Android 4.4.
```
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:507)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
	at de.greenrobot.dao.AbstractDao.moveToNextUnlocked(AbstractDao.java:442)
	at de.greenrobot.dao.AbstractDao.loadAllUnlockOnWindowBounds(AbstractDao.java:422)
	at de.greenrobot.dao.AbstractDao.loadAllFromCursor(AbstractDao.java:401)
	at de.greenrobot.dao.AbstractDao.loadAllAndCloseCursor(AbstractDao.java:191)
	at de.greenrobot.dao.InternalQueryDaoAccess.loadAllAndCloseCursor(InternalQueryDaoAccess.java:21)
	at de.greenrobot.dao.query.Query.list(Query.java:77)
	at de.greenrobot.dao.query.QueryBuilder.list(QueryBuilder.java:388)
	at fr.gaulupeau.apps.Poche.ui.ArticlesListFragment.getArticles(ArticlesListFragment.java:202)
	at fr.gaulupeau.apps.Poche.ui.ArticlesListFragment.updateList(ArticlesListFragment.java:169)
	at fr.gaulupeau.apps.Poche.ui.ArticlesListFragment.onResume(ArticlesListFragment.java:117)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2133)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1156)
	at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:950)
	at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1319)
	at android.support.v4.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManager.java:1705)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1646)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
	at android.view.View.measure(View.java:16522)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16522)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
	at android.view.View.measure(View.java:16522)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
	at android.view.View.measure(View.java:16522)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at android.view.View.measure(View.java:16522)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
	at android.view.View.measure(View.java:16522)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2566)
	at android.view.View.measure(View.java:16522)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5158)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
```

### PR DESCRIPTION
**Pull request by di72nn**
This PR:
* Makes `content` load lazily. To achieve that I had to move `content` to a separate table - I don't know how to make a field load lazily with Greendao otherwise. This probably fixes #413. Also improves performance of lists.
* Adds full-text search based on the [SQLite's FTS extension](https://www.sqlite.org/fts3.html) (improves #113). [Advanced queries](https://www.sqlite.org/fts3.html#full_text_index_queries) should be available now.
Currently `title` and `content` are separately indexed by FTS (can be used in queries like `title:linux`, see the previous link).

This PR implements [external content FTS tables](https://www.sqlite.org/fts3.html#_external_content_fts4_tables_), so there's no data duplication as in #871. Updating of FTS table is implemented using triggers. A lot of triggers \**sigh*\*.

The features are not so closely related, but seeing how FTS adds constraints, I decided to implement both in one PR.

### CODE REVIEW

File: app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java [hunk 1]
```diff
@@ -51,6 +53,21 @@ public void onUpgrade(Database db, int oldVersion, int newVersion) {
...
+
+                    ArticleContentDao.createTable(db, false);
+
+                    db.execSQL("insert into " + ArticleContentDao.TABLENAME +
+                            "(" + ArticleContentDao.Properties.Id.columnName +
+                            ", " + ArticleContentDao.Properties.Content.columnName + ")" +
+                            " select " + ArticleDao.Properties.Id.columnName + ", CONTENT" +
+                            " from " + ArticleDao.TABLENAME);
+
+                    // SQLite can't drop columns; just removing the data
```
Comment (Strubbl) [inline app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java]: we could only work around this, if we copy the data to a new table, drop this table and rename the new table to the old name. (e.g. https://stackoverflow.com/a/5987838/709697)
The question is, do we want to do this?

File: app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java [hunk 2]
```diff
@@ -51,6 +53,21 @@ public void onUpgrade(Database db, int oldVersion, int newVersion) {
...
+                    db.execSQL("update " + ArticleContentDao.TABLENAME + " set CONTENT = null;");
```
Comment (Strubbl) [inline app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java]: same as in line 73

File: app/src/main/java/fr/gaulupeau/apps/Poche/network/Updater.java [hunk 3]
```diff
@@ -215,7 +223,7 @@ private long performUpdate(ArticlesChangedEvent event, boolean full,
                     article = new Article(null);
                     article.setArticleId(id);
                     article.setTitle(apiArticle.title);
-                    article.setContent(apiArticle.content);
+                    article.setArticleContent(new ArticleContent(null, apiArticle.content));
```
Comment (Strubbl) [inline app/src/main/java/fr/gaulupeau/apps/Poche/network/Updater.java]: Shouldn't we put the id from L226 as id parameter here instead of null?

File: app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java [hunk 4]
```diff
@@ -68,6 +77,19 @@ public void onUpgrade(Database db, int oldVersion, int newVersion) {
                     db.execSQL("update " + ArticleContentDao.TABLENAME + " set CONTENT = null;");
                 }
 
+                if (oldVersion < 104) {
+                        Log.i(TAG, "Migrating to version " + 104);
```
Comment (Strubbl) [inline app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java]: white-space typo at the beginning of the line

File: app/src/main/java/fr/gaulupeau/apps/Poche/network/Updater.java (hunk 3 above)
Comment (di72nn) [reply app/src/main/java/fr/gaulupeau/apps/Poche/network/Updater.java]: Nope, this is local (SQLite) article ID, which is only available after the `article` is inserted.

File: app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java [hunk 5]
```diff
@@ -51,6 +53,21 @@ public void onUpgrade(Database db, int oldVersion, int newVersion) {
...
 
+                if (oldVersion < 103) {
+                    Log.i(TAG, "Migrating to version " + 103);
+
+                    ArticleContentDao.createTable(db, false);
+
+                    db.execSQL("insert into " + ArticleContentDao.TABLENAME +
+                            "(" + ArticleContentDao.Properties.Id.columnName +
+                            ", " + ArticleContentDao.Properties.Content.columnName + ")" +
+                            " select " + ArticleDao.Properties.Id.columnName + ", CONTENT" +
```
[the remark this answers is not in the document]
Comment (di72nn) [reply app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java]: That's a bit complicated. The basic idea is that old names (the hardcoded `CONTENT` here) will **never** change (because we can't retroactively change DB in older app versions). But the field `ArticleContentDao.Properties.Content.columnName` may actually change its value in a different version (column being renamed).

Actually, using ~constants~fields (that may change) in migrations is a bit dubious, because future field changes may affect old migrations. But it can be dealt with. Plus using fields lowers the probability of typos (except for not well readable string concatenations).

File: app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java (hunk 1 above)
Comment (di72nn) [reply app/src/main/java/fr/gaulupeau/apps/Poche/data/WallabagDbOpenHelper.java]: Nah, not worth the trouble.
Greendao doesn't provide any migrations, so its our job. And it doesn't care on this early stages of loading.

File: app/src/main/java/fr/gaulupeau/apps/Poche/data/OperationsHelper.java [hunk 6]
```diff
@@ -282,10 +284,13 @@ public static void deleteArticle(Context context, int articleID) {
     }
 
     public static void wipeDB(Settings settings) {
-        DbConnection.getSession().getArticleDao().deleteAll();
-        DbConnection.getSession().getTagDao().deleteAll();
-        DbConnection.getSession().getArticleTagsJoinDao().deleteAll();
-        DbConnection.getSession().getQueueItemDao().deleteAll();
+        DaoSession daoSession = DbConnection.getSession();
```
[the remark this answers is not in the document]
Comment (di72nn) [reply app/src/main/java/fr/gaulupeau/apps/Poche/data/OperationsHelper.java]: Sure, done.
